### ISSUE TITLE
weekender Events

### ISSUE THREAD

**Issue by simonpriller** [MasterMoritz/scraper#17]
zum scrapen für weekender bräuchte ich links im folgenden format

http://www.weekender.at/content.php?month=03&year=2016

ich würde vorschlagen, dass die seite immer 3 - 4 links (für die kommenden 3 - 4 monate) generiert, 3 monate sollten ausreichen. ich würde weekender dann 1mal pro woche scrapen

wenn die seite für die links steht bitte hier als comment verlinken

**Comment by Gogeta05** [comment]
soweit ich gesehen hab, sind die Links inzwischen alle für 1 Jahr im Kimono APi eingetragen und werden abgefragt. Ich mach das hier damit mal zu.
