### ISSUE TITLE
complete EventFactory

### ISSUE THREAD

**Issue by MasterMoritz** [MasterMoritz/scraper#5]
anyone is welcome to add an api parsing method to event factory

APIs
 - 5gig (MasterMoritz)(c64cb7c5f5cee46e507652d3cca7722c31fe38a0)

**Comment by Gogeta05** [comment]
wie krieg i am besten events von http://www.innsbruck.eventsuche.com/ via Kimono? EventHandler für IbkEvents fehlt dzt noch.

**Comment by YtGz** [comment]
Ich mach eine (wenn möglich eine einzelne für alle) Kimono API für:
- http://www.weekender.at/
- http://www.hafen.cc
- http://www.pmk.or.at/termine
- http://www.innsbruck.eventsuche.com/de/searchpage/results?categories[0]=69
- http://events.tt.com/veranstaltungen/innsbruck/musik

Endpoint Link füge ich ein, sobald ich fertig bin.

**Comment by simonpriller** [comment]
für http://www.weekender.at/ und http://www.hafen.cc hab ich in kimono bereits was
