### ISSUE TITLE
insert API Endpoints into Endpoints class

### ISSUE THREAD

**Issue by MasterMoritz** [MasterMoritz/scraper#7]
- write all of our API endpoints as a static final string into Endpoints class (including Kimono endpoints)

**Comment by simonpriller** [comment]
let me know if you want the access data for our kimono APIs I created an account for this project

**Comment by simonpriller** [comment]
hab einen kimono Account für die Gruppe gemacht. Soll ich die Zugangsdaten hier posten oder an die Gruppe mailen?

**Comment by Gogeta05** [comment]
dürfte erledigt sein. ich mach mal zu.
