### ISSUE TITLE
represent date in a more user-friendly format

### ISSUE THREAD

**Issue by MasterMoritz** [MasterMoritz/scraper#9]
when parsing the APIs the date should be stored in database in a more pleasing way 
( like "Saturday | 14.01.15 | 20:00").

**Comment by Gogeta05** [comment]
Maybe store the timestamp and display it the format you want?

**Comment by MasterMoritz** [comment]
use https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html with LocalDateTime and store the formatted String in database. should work.
